import { z } from "zod";

export const CreateComplaintSchema = z.object({
  ComplaintNo: z.number().int().min(1, "Complaint No must be greater than 0"),
  ComplaintDate: z.string().datetime().optional(),
  EnteredBy: z.string().min(1, "Entered By is required"),
  ComplaintSource: z.string().min(1, "Complaint Source is required"),
  CustomerCode: z.string().min(1, "Customer Code is required"),
  CustomerSource: z.string().optional(),
  SourceName: z.string().optional(),
  Contact: z.string().optional(),
  ProductServiceCode: z.string().optional(),
  ProductServiceDescription: z.string().optional(),
  StockReturnNo: z.number().int().optional(),
  BatchNo: z.string().optional(),
  Department: z.string().optional(),
  Problem: z.string().optional(),
  ProblemCategory: z.string().optional(),
  DefectCategory: z.string().optional(),
  ActionTaken: z.string().optional(),
  CreditNo: z.number().int().optional(),
  QuantityAffected: z
    .number()
    .int()
    .min(0, "Quantity Affected must be at least 0"),
  UOM: z.string().optional(),
  SampleAvailable: z.boolean().optional(),
  Cost: z.number().min(0, "Cost must be a positive value").optional(),
  ClaimNo: z.number().int().optional(),
  Status: z.string().optional(),
  Version: z.number().int().optional(),
  ProblemType: z.string().optional(),
  DepartmentCode: z.string().optional(),
  DepartmentContact: z.string().optional(),
  Priority: z.number().int().min(0, "Priority must be at least 0"),
  DueDate: z.string().datetime().nullable().optional(),
  CategoryCode: z.string().optional(),
  SubCategoryCode: z.string().optional(),
  ProductService: z.string().optional(),
  BatchType: z.string().optional(),
  EnteredTime: z.string().datetime().nullable().optional(),
  EstimatedReturnDate: z.string().datetime().nullable().optional(),
  MainProblemCategory: z.string().optional(),
  AuditNo: z.string().optional(),
  ImmediateAction: z.string().optional(),
  OtherType: z.string().optional(),
  FomaType: z.string().optional(),
  LineNo: z.string().optional(),
  SupplierCode: z.string().optional(),
  Auditor: z.string().optional(),
  ElementId: z.number().int().optional(),
  InvoiceNo: z.string().optional(),
  CarrierCode: z.string().optional(),
  Site: z.string().optional(),
  Internal: z.number().int().optional(),
  ExternalSource: z.string().optional(),
  InternalSource: z.string().optional(),
  OtherSource: z.string().optional(),
  DepartmentSource: z.string().optional(),
  InternalProblemEntry: z.string().optional(),
  QprType: z.number().int().min(1, "QprType must be at least 1"),
});

export type CreateComplaintType = z.infer<typeof CreateComplaintSchema>;
